preset: recommended

enabled:
    - concat_with_spaces
    - unalign_equals
    - no_spaces_after_function_name
    - no_spaces_inside_parenthesis
    - yoda_style

disabled:
    - concat_without_spaces
    - trailing_comma_in_multiline_array
    - not_operator_with_space

finder:
    path:
        - "src"
